<a href="https://colab.research.google.com/github/kunalsir98/Deep_learning/blob/main/SimpleRNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.5
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.15.0
backcall                         0.2.0
beautifulsoup4                   4.12.3
bidict                           0.23.1

In [2]:
from keras import Sequential
from keras.layers import Dense , SimpleRNN

In [9]:
model=Sequential()

In [10]:
model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1,activation='sigmoid'))

In [11]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_4 (SimpleRNN)    (None, 3)                 27        
                                                                 
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.get_weights()[0]

array([[-0.02234244, -0.78803426, -0.07219267],
       [ 0.8478028 , -0.7397687 , -0.20391953],
       [ 0.09507853,  0.34395832,  0.6099443 ],
       [ 0.7570277 ,  0.11986172, -0.27114564],
       [ 0.82151896, -0.21335512, -0.18333757]], dtype=float32)

In [15]:
model.get_weights()[0].shape

(5, 3)

In [16]:
from keras.datasets import  imdb

In [25]:
(X_train,y_train), (X_test,y_test)=imdb.load_data()

In [26]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [27]:
X_train.shape

(25000,)

In [28]:
X_test.shape

(25000,)

In [54]:
mylist=[]
for review in X_train:
  mylist.append(len(review))
min(mylist)

11

In [36]:
import numpy as np
sent=[

    'india won the world cup',
    'rohit played very well',
    'above all is my imagination',
    'bharat mata ki jay',
    'definetly we gone a win next worldcup'

]

In [37]:
from keras.preprocessing.text import Tokenizer

In [38]:
tokenizer=Tokenizer()

In [39]:

tokenizer.fit_on_texts(sent)

In [40]:

tokenizer.word_index

{'india': 1,
 'won': 2,
 'the': 3,
 'world': 4,
 'cup': 5,
 'rohit': 6,
 'played': 7,
 'very': 8,
 'well': 9,
 'above': 10,
 'all': 11,
 'is': 12,
 'my': 13,
 'imagination': 14,
 'bharat': 15,
 'mata': 16,
 'ki': 17,
 'jay': 18,
 'definetly': 19,
 'we': 20,
 'gone': 21,
 'a': 22,
 'win': 23,
 'next': 24,
 'worldcup': 25}

In [41]:
tokenizer.word_counts

OrderedDict([('india', 1),
             ('won', 1),
             ('the', 1),
             ('world', 1),
             ('cup', 1),
             ('rohit', 1),
             ('played', 1),
             ('very', 1),
             ('well', 1),
             ('above', 1),
             ('all', 1),
             ('is', 1),
             ('my', 1),
             ('imagination', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 1),
             ('jay', 1),
             ('definetly', 1),
             ('we', 1),
             ('gone', 1),
             ('a', 1),
             ('win', 1),
             ('next', 1),
             ('worldcup', 1)])

In [42]:
tokenizer.document_count

5

In [44]:
encoding=tokenizer.texts_to_sequences(sent)

In [45]:
encoding

[[1, 2, 3, 4, 5],
 [6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18],
 [19, 20, 21, 22, 23, 24, 25]]

In [46]:
from keras.utils import pad_sequences

In [48]:
pad_sequences(encoding,padding='post')

array([[ 1,  2,  3,  4,  5,  0,  0],
       [ 6,  7,  8,  9,  0,  0,  0],
       [10, 11, 12, 13, 14,  0,  0],
       [15, 16, 17, 18,  0,  0,  0],
       [19, 20, 21, 22, 23, 24, 25]], dtype=int32)

In [49]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [50]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [58]:
X_train=pad_sequences(X_train,padding='post',maxlen=50)

In [59]:
X_test=pad_sequences(X_test,padding='post',maxlen=50)

In [51]:
model=Sequential()

In [60]:
model.add(SimpleRNN(32,input_shape=(50,1)))

In [61]:
model.add(Dense(1,activation='sigmoid'))

In [62]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_5 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [64]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [65]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=5)

Epoch 1/5
782/782 [==============================] - 14s 15ms/step - loss: 0.6950 - accuracy: 0.5013 - val_loss: 0.6942 - val_accuracy: 0.5025
Epoch 2/5
782/782 [==============================] - 13s 16ms/step - loss: 0.6929 - accuracy: 0.5086 - val_loss: 0.6957 - val_accuracy: 0.5004
Epoch 3/5
782/782 [==============================] - 13s 16ms/step - loss: 0.6931 - accuracy: 0.5018 - val_loss: 0.6960 - val_accuracy: 0.5026
Epoch 4/5
782/782 [==============================] - 13s 17ms/step - loss: 0.6925 - accuracy: 0.5145 - val_loss: 0.6954 - val_accuracy: 0.5022
Epoch 5/5
782/782 [==============================] - 11s 14ms/step - loss: 0.6929 - accuracy: 0.5039 - val_loss: 0.6939 - val_accuracy: 0.5067


In [66]:
model.predict(X_test)

782/782 [==============================] - 3s 4ms/step


array([[0.49265838],
       [0.49265838],
       [0.49265838],
       ...,
       [0.49265838],
       [0.49265838],
       [0.49265838]], dtype=float32)